### ISSUE TITLE
BLAS/LAPACK routine `DSYRK` gave error code -7

### ISSUE THREAD

**Issue by ecoronado92** [merliseclyde/BAS#37] opened 2018-10-30 21:41 UTC
**Describe the bug**
When knitting the attache Rmd Document I get this error.

**To Reproduce**

See attached file (remove .txt extension and run on RStudio)
[test_BAS.Rmd.txt](https://github.com/merliseclyde/BAS/files/2531757/test_BAS.Rmd.txt)

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS Mojave 

**Additional context**
test in versions  from both CRAN and github repo, locally installed

**Comment by merliseclyde** [comment] 2018-11-01 02:07
Ahh - the problem is that the code to create the test/training data for the `caravan` data redefines `train` for the simulated data.  This is leads to `df[train,]` to have zero rows, which when passed to the functions does not catch that there `n` is zero.

Will need to add checks to catch this and throw an error (plus unit test for case when n=0)

Thanks! m

**Comment by ecoronado92** [comment] 2018-11-01 02:08
I see! Ok that makes sense - glad I was able to help with this bug :)

**Comment by merliseclyde** [comment] 2020-11-01 18:09
Addressed in release BAS 1.5.4 (forgot to close issue :-)

**Closed** 2020-11-01 18:09 UTC
Labels: bug
