### ISSUE TITLE
error in hypergeometric1F1

### ISSUE THREAD

**Issue by karmabe1iver** [merliseclyde/BAS#79] opened 2024-03-29 09:52 UTC
library(BAS)

beta_poisson_pmf1 <- function(x, alpha, beta) {
  numerator <- gamma(x + alpha) * gamma(alpha + beta) *hypergeometric1F1(x + alpha, x + alpha + beta, -1)
  denominator <- gamma(x + 1) * gamma(alpha) * gamma(x + alpha + beta)
  result <- numerator / denominator
  return(result)
}
beta_poisson_pmf1(1,2,3)  probability mass function is negative is getting

**Comment by merliseclyde** [comment] 2024-03-30 16:13
Duplicate of #78 

Please read the documentation and use the flag log=FALSE as shown in reply to issue #78

**Closed by merliseclyde** 2024-03-30 16:13 UTC
Labels: wontfix
